entraid_groups:
  - names: Grp-Entraid-Glb-Dataplatfform-Analysts-User
  - names: Grp-Entraid-Glb-Dataplatfform-Engineers-User
  - names: Grp-Entraid-Glb-Dataplatfform-Operators-User
  - names: Grp-Entraid-Glb-Dataplatfform-Searchers-User
  - names: Grp-Entraid-Glb-Dataplatfform-Datascientists-User
  - names: Grp-Entraid-Glb-Dataplatfform-Dataplatform-User
  - names: Grp-Entraid-Glb-Dataplatfform-Admin-User

account_groups:
  - names: Analysts
    role: User
    members:
      - Grp-Entraid-Glb-Dataplatfform-Analysts-User
      - Grp-Entraid-Glb-Dataplatfform-Dataplatform-User

  - names: Engineers
    role: User
    members:
      - Grp-Entraid-Glb-Dataplatfform-Engineers-User
      - Grp-Entraid-Glb-Dataplatfform-Searchers-User

  - names: Operators
    role: User
    members:
      - Grp-Entraid-Glb-Dataplatfform-Operators-User

  - names: Searchers
    role: User
    members:
      - Grp-Entraid-Glb-Dataplatfform-Searchers-User

  - names: Datascientists
    role: User
    members:
      - Grp-Entraid-Glb-Dataplatfform-Datascientists-User

  - names: Dataplatform
    role: User
    members:
      - Grp-Entraid-Glb-Dataplatfform-Dataplatform-User

  - names: Admin
    role: Admin
    members:
      - Grp-Entraid-Glb-Dataplatfform-Admin-User

  - names: AccountAdmin
  - names: MetastoreAdmin
  - names: WorkspaceAdmin

entraid_spn:
  - names: App-Databricks-frc-dev
  - names: App-Databricks-frc-uat
  - names: App-Databricks-frc-prd
